name: Deploy Fullstack App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      # Deploy frontend from the `frontend` folder
      - name: Deploy Frontend to Vercel
        working-directory: ./frontend
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_SCOPE }}

      # Deploy backend via Render deploy hook
      - name: Deploy Backend to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
# name: CI/CD Pipeline
